#!/bin/sh

ENABLED=yes
PROCS=poolheatd
ARGS=""
PREARGS=""
DESC="poolheat Whatsminer thermal controller"
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
