"""Whatsminer management library (public API V1/V2/V3 + NetPacket + WMOC)."""

from __future__ import annotations

from .api import (
    ApiCommand,
    V1_ONLY_CMDS,
    V1_READ_CMDS,
    V1_WRITE_CMDS,
    V2_READ_CMDS,
    V2_WRITE_CMDS,
    V3_ENCRYPTED_PARAMS,
    V3_GET_CMDS,
    V3_SET_CMDS,
    WhatsminerV1,
    WhatsminerV2,
    WhatsminerV3,
    all_commands,
    api_summary_table,
    commands_by_family,
)
from .client import MinerClient, detect_api
from .errors import AuthError, CommandError, ProtocolError, WhatsminerError
from .models import BoardInfo, ErrorCode, MinerStatus, PoolInfo
from .protocol import (
    KEY0,
    KEY1,
    KEY2,
    KEY_A,
    KEY_B,
    KEYA,
    KEYB,
    STATIC_AES_KEYS,
    PARAM_INFO,
    Cmd,
    NetPacket,
    NetPacketClient,
    Param,
    PerformanceMode,
    PowerMode,
)
from .support import (
    DEFAULT_M60_J_PER_TH,
    available_languages,
    compare_reported_vs_model_power,
    describe_error,
    enrich_error_codes,
    estimate_dual_wall_power,
    estimate_history_wall_power,
    estimate_power_from_hashrate,
    list_codes,
    parse_agp_preset_label,
    resolve_error,
    resolve_errors,
    resolve_model_efficiency,
)
from .universal import (
    Capabilities,
    PublicApi,
    Transport,
    UniversalMiner,
    probe_capabilities,
)
from .web import (
    LuCIClient,
    LuCIError,
    WMOCClient,
    WMOC_HISTORY_PATH,
    WMOC_HTML_MARKERS,
    WMOC_MARKER_PATHS,
    WMOC_MODULES,
    WMOC_PRIMARY_PATH,
    WMOC_TOOLS_PATH,
    detect_wmoc,
)

__all__ = [
    # façade
    "MinerClient",
    "UniversalMiner",
    "Capabilities",
    "PublicApi",
    "Transport",
    "detect_api",
    "probe_capabilities",
    # public API
    "WhatsminerV1",
    "WhatsminerV2",
    "WhatsminerV3",
    "V1_READ_CMDS",
    "V1_WRITE_CMDS",
    "V1_ONLY_CMDS",
    "V2_READ_CMDS",
    "V2_WRITE_CMDS",
    "V3_GET_CMDS",
    "V3_SET_CMDS",
    "V3_ENCRYPTED_PARAMS",
    "ApiCommand",
    "all_commands",
    "commands_by_family",
    "api_summary_table",
    # private protocol
    "NetPacketClient",
    "NetPacket",
    "Cmd",
    "Param",
    "PerformanceMode",
    "PowerMode",
    "KEY0",
    "KEY1",
    "KEY2",
    "KEY_A",
    "KEY_B",
    "KEYA",
    "KEYB",
    "STATIC_AES_KEYS",
    "PARAM_INFO",
    # web / WMOC
    "LuCIClient",
    "LuCIError",
    "WMOCClient",
    "detect_wmoc",
    "WMOC_MODULES",
    "WMOC_MARKER_PATHS",
    "WMOC_PRIMARY_PATH",
    "WMOC_TOOLS_PATH",
    "WMOC_HISTORY_PATH",
    "WMOC_HTML_MARKERS",
    # power / errors i18n
    "estimate_power_from_hashrate",
    "estimate_dual_wall_power",
    "compare_reported_vs_model_power",
    "estimate_history_wall_power",
    "parse_agp_preset_label",
    "resolve_model_efficiency",
    "DEFAULT_M60_J_PER_TH",
    "describe_error",
    "resolve_error",
    "resolve_errors",
    "enrich_error_codes",
    "available_languages",
    "list_codes",
    # models / exceptions
    "MinerStatus",
    "PoolInfo",
    "BoardInfo",
    "ErrorCode",
    "WhatsminerError",
    "AuthError",
    "ProtocolError",
    "CommandError",
]

__version__ = "0.6.0"
